name: Christian Fei's Blog
description: A blog about my programming ramblings and other weird stuff
meta_description: A blog about my programming ramblings and other weird stuff

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough","with_toc_data"]
# highlighter: pygments

paginate: 10
baseurl: /
domain_name: 'http://christian.fei.ninja'
google_analytics: 'UA-57238829-1'
disqus_shortname: 'christianfei'

# Details for the RSS feed generator
url:            'http://christian.fei.ninja'
author:         'Christian Fei'
authorTwitter:  'christian_fei'

permalink:       /:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
