# Site settings
title: Christian Fei's blog
email: christian@fei.ninja
description: >
  This is just a test.
permalink: /:title/
baseurl: ""
url: "http://christian.fei.ninja"
twitter_username: christian_fei
github_username: christian-fei

# Build settings
markdown: redcarpet
