# Site settings
title: Christian Fei's Blog
desc: "A blog about my programming ramblings with JavaScript and other weird stuff"
email: christian@fei.ninja
description: Christian Fei's Blog
permalink: /:title/
baseurl: ""
url: "http://christian.fei.ninja"
twitter_username: christian_fei
github_username: christian-fei

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
