#!/bin/bash

MAIN_CSS=main.css
MAIN_JS=main.js
HTML_TEMPLATE=templates/html.template
PANDOC_PARAMS="--atx-headers --template=$HTML_TEMPLATE --from markdown --to=html5 --standalone -H head.html -B header.html --metadata-file=posts/index.yml"
DIST=dist

printf "\n💯  build\n"
printf "\n⛏ index page"

mkdir -p $DIST
rm -rf $DIST/*
pandoc $PANDOC_PARAMS index.md -o $DIST/index.html

printf "\n⛏ about page"
mkdir -p $DIST/about
pandoc $PANDOC_PARAMS about.md -o $DIST/about.html
cp $DIST/about.html $DIST/about/index.html

mkdir -p $DIST/posts

echo "posts: " > posts/index.yml

# create posts/index.yml
for file in $(ls -lr posts/*.md)
do
  if [[ -f $file ]]; then
    name=$(basename ${file%.*})
    # echo "$name"
    echo "  - $name" >> posts/index.yml
  fi
done

# build each post
printf "\n⛏ building posts\n"
for file in posts/*.md
do
  if [ -f $file ] && [ "$file" != "posts/index.md" ]; then
    name=$(basename ${file%.*})
    # echo "⛏ $name"
    printf "."
    pandoc $PANDOC_PARAMS posts/$name.md -o $DIST/posts/$name.html
    mkdir -p $DIST/posts/$name
    cp $DIST/posts/$name.html $DIST/posts/$name/index.html
  fi
done

printf "\n⛏ copying assets"
cp -r assets dist/

printf "\n⛏ copying styles\n"
cp -r $MAIN_CSS dist/$MAIN_CSS

printf "\n⛏ copying scripts\n"
cp -r $MAIN_JS dist/$MAIN_JS
