#!/bin/bash

MAIN_CSS=main.css
MAIN_JS=main.js
PANDOC_PARAMS="--atx-headers --template=templates/html.template --from markdown --to=html5 -H head.html -B header.html --metadata-file=index.yml"
DIST=dist

printf "\n💯  build\n"


printf "\n⛏ index page"
mkdir -p $DIST
rm -rf $DIST/*
pandoc $PANDOC_PARAMS index.md -o $DIST/index.html

printf "\n⛏ about page"
mkdir -p $DIST/about
pandoc $PANDOC_PARAMS about.md -o $DIST/about.html
cp $DIST/about.html $DIST/about/index.html

printf "\n⛏ pocket-items page"
mkdir -p $DIST/pocket-items
pandoc $PANDOC_PARAMS pocket-items.md -o $DIST/pocket-items.html
cp $DIST/pocket-items.html $DIST/pocket-items/index.html

mkdir -p $DIST/posts

printf "\n⛏ copying assets"
cp -r assets dist/

printf "\n⛏ copying styles\n"
cp -r $MAIN_CSS dist/$MAIN_CSS
cp github-contributions.svg  dist/github-contributions.svg

printf "\n⛏ copying scripts\n"
cp -r $MAIN_JS dist/$MAIN_JS

printf "\n⛏ copying synced.json\n"
cp synced.json dist/synced.json

printf "\n⛏ copying github-contributions.svg\n"
cp github-contributions.svg dist/github-contributions.svg

printf "\n⛏ building index.yml\n"
echo "posts: " > index.yml
for file in $(ls -lr posts/*.md)
do
  if [ -f $file ] && [ "$file" != "posts/index.md" ]; then
    name=$(basename ${file%.*})
    echo "  - $name" >> index.yml
  fi
done

printf "\n⛏ building posts\n"
for file in posts/*.md
do
  if [ -f $file ] && [ "$file" != "posts/index.md" ]; then
    name=$(basename ${file%.*})
    # echo "⛏ $name"
    printf "."
    pandoc $PANDOC_PARAMS posts/$name.md -o $DIST/posts/$name.html
    mkdir -p $DIST/posts/$name
    cp $DIST/posts/$name.html $DIST/posts/$name/index.html
  fi
done
