#!/usr/bin/env node
var exec   = require('child_process').exec
var today  = new Date()
 , day     = pad(today.getDate())
 , month   = pad(today.getMonth()+1)
 , year    = today.getFullYear()

var date  = [year,month,day].join('-') + '-'
 , title         = process.argv.splice(2).join(' ')
 , titleDashed   = title.split(' ').join('-')
 , extension     = '.md'
 , fullTitle     = [date,titleDashed,extension].join('')
 , postPath      = '_posts/'+fullTitle

var cmd = 'echo '+ postContents(title,date) + ' > ' + postPath
exec(cmd)

function pad(x){return (x>=10)?x:'0'+x}

function postContents(title, date){
  return [
  "---",
  "title: '"+ title +"'",
  "date: "+ date,
  "layout: post",
  "---"].join('\n')
}
