#!/usr/bin/env node
var exec   = require('child_process').exec
var today  = new Date()
 , day     = pad(today.getDate())
 , month   = pad(today.getMonth()+1)
 , year    = today.getFullYear()

var extension     = '.md'
var date  = [year,month,day].join('-')
var title         = process.argv.splice(2).join(' ')
var titleDashed   = title.split(' ').join('-')

titleDashed = titleDashed.replace("'", '')
titleDashed = titleDashed.replace('"', '')
titleDashed = titleDashed.replace(',', '')

var fullTitle     = [date,'-',titleDashed,extension].join('')
var postPath      = '_posts/'+fullTitle


var cmd = 'echo "'+ postContents(title,date) + '" > ' + postPath
exec(cmd, function(err){
  if(err) {console.log('there was an error')}
  console.log('created file '+postPath)
})

function pad(x){return (x>=10)?x:'0'+x}

function postContents(title, date){
  title = title.replace("'", '')
  return [
  "---",
  "title: '"+ title +"'",
  "date: "+ date,
  "layout: post",
  "---"].join('\n')
}
