#!/usr/bin/env node

const {readFileSync, writeFileSync} = require('fs')
const {resolve} = require('path')

const discoverPath = resolve(__dirname, '_data', 'discover.yml')

const discoverContents = readFileSync(discoverPath, {encoding: 'utf-8'})

const args = process.argv.slice(2)
let title = args[0]
let description = args[1]
let url = args[2]
const date = new Date().toISOString().substring(0, 10)

if (!title) throw new Error('"title" is required, see `discover` for more info')

if (/^http/.test(title)) {
  url = title
  title = null
}

if (/^http/.test(description)) {
  url = description + ''
  description = null
}

const newDiscover = []
if (title) newDiscover.push(`title: "${title}"`)
if (description) newDiscover.push(`description: "${description}"`)
if (url) newDiscover.push(`url: "${url}"`)
newDiscover.push(`date: "${date}"`)

const newDiscoverContents = newDiscover.reduce((acc, curr, index) => {
  const line = `${(index === 0) ? '-' : ' '} ${curr}\n`
  return acc + line
}, '')

writeFileSync(discoverPath, `${newDiscoverContents}${discoverContents}`, {encoding: 'utf-8'})

process.stdout.write(readFileSync(discoverPath, {encoding: 'utf-8'}))
