#!/usr/bin/env node

const {readFileSync, writeFileSync} = require('fs')
const {resolve} = require('path')

const discoverPath = resolve(__dirname, '_data', 'discover.yml')

const discoverContents = readFileSync(discoverPath, {encoding: 'utf-8'})

const args = process.argv.slice(2)
let title = args[0]
let description = args[1]
let url = args[2]
const date = new Date().toISOString().substring(0, 10)

if (!title) throw new Error('"title" is required, see `discover` for more info')

if (/^http/.test(title)) {
  url = title
  title = null
}

if (/^http/.test(description)) {
  url = description + ''
  description = null
}

const newDiscover = `
-${title ? ` title: "${title}"` : ''}${description ? ` description: "${description}"` : ''}${url ? ` url: "${url}"` : ''}
  date: "${date}"
`.trim()

writeFileSync(discoverPath, `${newDiscover}\n${discoverContents}`, {encoding: 'utf-8'})

process.stdout.write(readFileSync(discoverPath, {encoding: 'utf-8'}))
